name:                tomado
version:             0.1.0.0
github:              amderbar/tomado
license:             BSD-3-Clause
author:              amderbar
maintainer:          amderbar@gmail.com
copyright:           amderbar

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/amderbar/tomado#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- placeholders
- beam-core
- beam-migrate
- beam-sqlite
- sqlite-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  tomado-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - tomado
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  tomado-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - tomado
    - hspec
    - hspec-discover

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
